In [1]:
import pandas as pd
import numpy as np
import matplotlib as pl
import seaborn as sns

In [2]:
df=pd.read_csv('C:/Users/sahil/Desktop/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
df.size

2000

In [6]:
df.shape

(400, 5)

In [7]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [8]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [9]:
df1=df
q_data=pd.get_dummies(df1.Gender)
q_data

Female  Male
0         0     1
1         0     1
2         1     0
3         1     0
4         0     1
..      ...   ...
395       1     0
396       0     1
397       1     0
398       0     1
399       1     0

[400 rows x 2 columns]

In [11]:
df2=df1.join(q_data)
df2

User ID  Gender  Age  EstimatedSalary  Purchased  Female  Male
0    15624510    Male   19            19000          0       0     1
1    15810944    Male   35            20000          0       0     1
2    15668575  Female   26            43000          0       1     0
3    15603246  Female   27            57000          0       1     0
4    15804002    Male   19            76000          0       0     1
..        ...     ...  ...              ...        ...     ...   ...
395  15691863  Female   46            41000          1       1     0
396  15706071    Male   51            23000          1       0     1
397  15654296  Female   50            20000          1       1     0
398  15755018    Male   36            33000          0       0     1
399  15594041  Female   49            36000          1       1     0

[400 rows x 7 columns]

In [12]:
df2.drop(['Gender'], axis=1)

User ID  Age  EstimatedSalary  Purchased  Female  Male
0    15624510   19            19000          0       0     1
1    15810944   35            20000          0       0     1
2    15668575   26            43000          0       1     0
3    15603246   27            57000          0       1     0
4    15804002   19            76000          0       0     1
..        ...  ...              ...        ...     ...   ...
395  15691863   46            41000          1       1     0
396  15706071   51            23000          1       0     1
397  15654296   50            20000          1       1     0
398  15755018   36            33000          0       0     1
399  15594041   49            36000          1       1     0

[400 rows x 6 columns]

In [16]:
X = pd.DataFrame(df2, columns = ['Age', 'EstimatedSalary'])
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [17]:
Y = pd.DataFrame(df2, columns = ['Purchased'])
Y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [19]:
X_train , X_test, Y_train , Y_test = train_test_split(X,Y,test_size = 0.30)

In [20]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

In [21]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [22]:
Classifier = LogisticRegression(random_state=0)
Classifier.fit(X_train, Y_train)

C:\Users\sahil\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [23]:
Y_pred = Classifier.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
cm

array([[76,  5],
       [10, 29]], dtype=int64)

In [26]:
TP = cm[0,[0]]
FP = cm[0,[1]]
FN = cm[1,[0]]
TN = cm[1,[1]]

In [27]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)*100
accuracy

87.5

In [28]:
ACCURACY = (TP+TN)/(TP+TN+FP+FN)
ACCURACY

array([0.875])

In [29]:
PRECISION = (TP)/(TP+FP)
PRECISION

array([0.9382716])

In [30]:
SPECIFICITY = (TN)/(TN+FP)
SPECIFICITY

array([0.85294118])

In [31]:
RECALL = (TP)/(TP+FN)
RECALL

array([0.88372093])

In [32]:
ERROR_RATE = (FP+FN)/(TP+TN+FP+FN)
ERROR_RATE

array([0.125])